logging:
  level:
    ru.practicum.stats.aggregator: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO
      apache.kafka: WARN

aggregator:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
        "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
        "value.serializer": "ru.practicum.stats.avro.serializer.GeneralAvroSerializer"
        "linger.ms": 0
      topic: "stats.events-similarity.v1"

    consumer:
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
        "enable.auto.commit": false
        "group.id": "stats.aggregator.actions"
        "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer"
        "value.deserializer": "ru.practicum.stats.avro.deserializer.UserActionDeserializer"
      topic: "stats.user-actions.v1"
      poll-timeout: 100ms