server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        max-attempts: 10
        max-interval: 10000

  sql:
    init:
      mode: always
      platform: h2

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    ru.practicum.user.service: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: INFO

# Общая настройка для Feign Circuit Breaker
feign:
  circuitbreaker:
    enabled: true

# Resilience4j Circuit Breaker конфигурация
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 50
        failure-rate-threshold: 50
    instances:
      user-service:
        sliding-window-size: 30
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 7
        automatic-transition-from-open-to-half-open-enabled: true
      event-service:
        sliding-window-size: 30
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 7
        automatic-transition-from-open-to-half-open-enabled: true